# -*- coding: utf-8 -*-
"""Profissao Analista de dados M18 Exercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_7uRHeCv8p8dJ10aqdMQFqBxPST4UNlN

<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Análise de Dados: Controle de Versão II
Caderno de **Exercícios**<br>
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Adicionar e salvar;</li>
  <li>Visualizar e reverter;</li>
  <li>Persistir e atualizar.</li>
</ol>

---

# **Exercícios**

## 1\. Setup

Para realizar os exercicios vamos configurar o `git` e trazer o projeto do GitHub para a a máquina virtual do Google Colab (ou na sua máquina local, as instruções são as mesmas). Para tanto, replique as atividades expostas na aula 1 deste módulo.

### **1.1. Autenticação**

Nesta etapa, vamos configura o `git` com suas credenciais.
"""

import os

username = "italofvaz" # insira o seu nome de usuário do git
os.environ["GITHUB_USER"] = username

!git config --global user.name "${GITHUB_USER}"

import os
from getpass import getpass

usermail = getpass()
os.environ["GITHUB_MAIL"] = usermail

!git config --global user.email "${GITHUB_MAIL}"

import os
from getpass import getpass

usertoken = getpass()
os.environ["GITHUB_TOKEN"] = usertoken

"""### **1.2. Projeto**

Nesta etapa, vamos trazer o projeto do GitHub para máquina local.
"""

!git clone https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/italofvaz/da-ebac.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/da-ebac/

"""---

## 2\. Preço da gasolina

O código abaixo gera um arquivo com o preço médio de venda da gasolina na cidade de São Paulo nos 10 primeiros dias de Julho de 2021.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile gasolina.csv
# dia,venda
# 1,5.11
# 2,4.99
# 3,5.02
# 4,5.21
# 5,5.07
# 6,5.09
# 7,5.13
# 8,5.12
# 9,4.94
# 10,5.03

"""### **2.1. Desenvolvimento**

Gere uma gráfico de linha utilizando os dados do arquivo `gasolina.csv` com o dia no eixo `x`
 e o seu preço no eixo `y` utilizando os pacotes Python de sua preferência, como o Pandas e o Seaborn. Salve o gráfico no arquivo `gasolina.png` e o seu código Python de geração no arquivo `gasolina.py`.
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

gasolina_df = pd.read_csv("gasolina.csv")
gasolina_df.head(20)

"""Diferenças entre Matplotlib e Seaborn

Matplotlib: Ideal para personalização avançada e controle total sobre os elementos do gráfico.

Seaborn: Mais amigável e estilizado, com melhor suporte a dados em DataFrames (como do pandas).
"""

#grafico com Matplotlib

x = gasolina_df['dia']
y = gasolina_df['venda']


plt.plot(x, y, marker='o', linestyle='-', color='b', label='preco Gasolina')

plt.title("Gasolina", fontdict={"fontsize":16})
lgnd = plt.legend(prop={"size":15})
plt.xlabel("Eixo X")
plt.ylabel("Eixo Y")
plt.legend()  # Mostrar a legenda
plt.grid(True)



plt.savefig('gasolina.png', format='png', dpi=300, bbox_inches='tight')

# Grafico com Seaborn

data = pd.DataFrame(gasolina_df[['dia', 'venda']])
grafico = sns.lineplot(data=data, x="dia", y="venda" , marker='o', label='Crescimento')
grafico.set(title='Gasolina', xlabel='dias', ylabel='preco');

"""### **2.2. Git**

Utilizando os comandos do `git`, adicione e "commite" os arquivos gerados (base, código Python e gráfico).
"""

!git status

!git add .

!git commit -m "ätualizacao do codigo"
!git status

"""### **2.3. Github**

Utilizando os comandos do `git`, envie o seu commit para o GitHub.
"""

!git push origin main
!git status

"""---

## 3\. Arquivo README.md

O arquivo README.md é a porta de entrada do seu projeto, é ele que será renderizado quando o seu projeto for acessado, portanto, é importante que ele esteja bem escrito. Alguns exemplos:

- [Pandas](https://github.com/pandas-dev/pandas);
 - [Seaborn](https://github.com/mwaskom/seaborn);
 - [Spark Cluster on Docker](https://github.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker), esse projeto é meu! :)

### **3.1. Desenvolvimento**
"""

!cat /content/sample_data/README.md





file_path = '/content/da-ebac/README.md'

with open(file_path, 'w') as f:
    f.write(" # Análise de Preços da Gasolina\n\nEste repositório contém um script Python para gerar gráficos de linhas mostrando a evolução do preço da gasolina com base em dados de um arquivo CSV. \n\n ## Conteúdo \n\n - **gasolina.py**: Script Python para análise e geração do gráfico. \n\n - **gasolina.csv**: Dados de entrada com datas e preços. \n\n - **gasolina.png**: Gráfico gerado pelo script.")

!git add .
!git status

!git commit -m "arquivo README atualiza"

!git push origin main
!git status

"""Altere o arquivo README.md com informações sobre seu repositório, inclua um título e uma breve descrição do repositório (no mínimo).

> **Dica**: o README.md pode ser configurado utilizando o padrão **markdown**, o mesmo que utilizamos nas células de texto aqui no Google Colab.
"""